services:
  postgres:
    image: postgres:16
    container_name: sentiment-postgres
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sentiment_pgdata:/var/lib/postgresql/data

volumes:
  sentiment_pgdata:
